spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: ${MYSQL_URL:jdbc:h2:~/test}
    username: ${MYSQL_USERNAME:sa}
    password: ${MYSQL_PASSWORD:}
  h2:
    console:
      enabled: true
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    hibernate:
      ddl-auto: create
auth:
  jwt:
    secret: ${JWT_SECRET:upgrade_test}
    exp:
      access: ${JWT_ACCESS_EXP:3600}
      refresh: ${JWT_REFRESH_EXP:3600}
    header: ${JWT_HEADER:Authorization}
    prefix: ${JWT_PREFIX:Bearer}
image:
  file:
    path: ${FILE_PATH:test-path}
cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: ${S3_BUCKET:test-bucket}