spring:
  profiles:
    include:
      - aws
      - credentials
    active: ${ACTIVE_PROFILE:dev}

---

spring:
  profiles: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password:
  h2:
    console:
      enabled: true
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    hibernate:
      ddl-auto: create
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 215MB
      file-size-threshold: 2KB
auth:
  jwt:
    secret: ${JWT_SECRET:upgrade_test}
    exp:
      access: ${JWT_ACCESS_EXP:3600}
      refresh: ${JWT_REFRESH_EXP:3600}
    header: ${JWT_HEADER:Authorization}
    prefix: ${JWT_PREFIX:Bearer}
file:
  path:
    profile-image: ${PROFILE_IMAGE_PATH}

---

spring:
  profiles: production
  datasource:
    driver-class-name: ${MYSQL_DRIVER_CLASS:org.h2.Driver}
    url: ${MYSQL_URL:jdbc:h2:~/test}
    username: ${MYSQL_USERNAME:sa}
    password: ${MYSQL_PASSWORD:}
  jackson:
    property-naming-strategy: SNAKE_CASE
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 215MB
      file-size-threshold: 2KB
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
auth:
  jwt:
    secret: ${JWT_SECRET:upgrade_test}
    exp:
      access: ${JWT_ACCESS_EXP:3600}
      refresh: ${JWT_REFRESH_EXP:3600}
    header: ${JWT_HEADER:Authorization}
    prefix: ${JWT_PREFIX:Bearer}
image:
  file:
    path: ${FILE_PATH:filepath}