cloud:
  aws:
    credentials:
      accessKey: ${AWS_CREDENTIAL_ACCESS:access-key}
      secretKey: ${AWS_CREDENTIAL_SECRET:secret-key}
      profile-name: ${AWS_CREDENTIAL_NAME:profile-name}
      profile-path: ${AWS_CREDENTIAL_PATH:/}