cloud:
  aws:
    stack:
      auto: false
    credentials:
      accessKey: ${AWS_CREDENTIAL_ACCESS:access-key}
      secretKey: ${AWS_CREDENTIAL_SECRET:secret-key}
aws:
  s3:
    access-key: ${AWS_CREDENTIAL_ACCESS:access-key}
    secret-key: ${AWS_CREDENTIAL_SECRET:secret-key}